# Generated by Django 6.0.5 on 2026-05-13 11:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=16, unique=True)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('day_of_week',),
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SpecialSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_mode', models.CharField(choices=[('SINGLES', 'Singles'), ('DOUBLES', 'Doubles')], max_length=10)),
                ('player_type', models.CharField(choices=[('MEMBER', 'Member'), ('NON_MEMBER', 'Non member')], max_length=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-valid_from', 'game_mode', 'player_type'),
                'indexes': [models.Index(fields=['game_mode', 'player_type', 'active'], name='reservation_game_mo_b7ba3f_idx'), models.Index(fields=['valid_from', 'valid_to'], name='reservation_valid_f_238f41_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecurringReservationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('days_of_week', models.JSONField(default=list)),
                ('start_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_rules', to='reservations.court')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('court_id', 'start_time', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation_type', models.CharField(choices=[('NORMAL', 'Normal'), ('CLASS', 'Class')], default='NORMAL', max_length=10)),
                ('game_mode', models.CharField(blank=True, choices=[('SINGLES', 'Singles'), ('DOUBLES', 'Doubles')], max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_phone', models.CharField(max_length=50)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('CANCELLATION_REQUESTED', 'Cancellation requested')], default='CONFIRMED', max_length=30)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_reservations', to=settings.AUTH_USER_MODEL)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.court')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('recurring_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reservations', to='reservations.recurringreservationrule')),
            ],
            options={
                'ordering': ('start_datetime', 'court_id'),
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email')], max_length=12)),
                ('destination', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=8)),
                ('error_message', models.TextField(blank=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='reservations.reservation')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester_name', models.CharField(max_length=150)),
                ('requester_phone', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_cancellation_requests', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='reservations.reservation')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReservationPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_member', models.BooleanField(default=False)),
                ('price_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='reservations.reservation')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='BlockedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('block_type', models.CharField(choices=[('TOURNAMENT', 'Tournament'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blocked_slots', to=settings.AUTH_USER_MODEL)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocked_slots', to='reservations.court')),
            ],
            options={
                'ordering': ('start_datetime', 'court_id'),
                'indexes': [models.Index(fields=['court', 'start_datetime'], name='reservation_court_i_add482_idx'), models.Index(fields=['court', 'end_datetime'], name='reservation_court_i_a60315_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['court', 'start_datetime'], name='reservation_court_i_5e324f_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['court', 'end_datetime'], name='reservation_court_i_78f3bc_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='reservation_status_f1a03a_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('reservation_type', 'CLASS')), fields=('recurring_rule', 'court', 'start_datetime'), name='uniq_class_per_rule_court_start'),
        ),
    ]
