# Generated by Django 6.0.5 on 2026-06-16 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_is_paid_reservation_paid_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('mercadopago', 'Mercado Pago')], default='mercadopago', max_length=20)),
                ('payment_type', models.CharField(choices=[('total', 'Total'), ('player', 'Player'), ('partial', 'Partial')], max_length=12)),
                ('preference_id', models.CharField(blank=True, max_length=120)),
                ('payment_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('external_reference', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_process', 'In process'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('amount_mismatch', 'Amount mismatch')], default='pending', max_length=24)),
                ('status_detail', models.CharField(blank=True, max_length=255)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('identification_decimal', models.DecimalField(decimal_places=2, default='0.19', max_digits=4)),
                ('mp_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_received', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('payment_url', models.URLField(blank=True, max_length=500)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='mp_external_reference_base',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='reservation',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('pending_payment', 'Pending payment'), ('partial_payment', 'Partial payment'), ('paid', 'Paid'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending_payment', max_length=24),
        ),
        migrations.AddField(
            model_name='reservation',
            name='requires_admin_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['payment_status'], name='reservation_payment_060592_idx'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='reservations.reservationplayer'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='reservations.reservation'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['reservation', 'status'], name='reservation_reserva_62c499_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['external_reference'], name='reservation_externa_479ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment_id'], name='reservation_payment_91e121_idx'),
        ),
    ]
