# Generated by Codex on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_paymenttransaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="provider",
            field=models.CharField(
                choices=[
                    ("mercadopago", "Mercado Pago"),
                    ("cash", "Cash"),
                ],
                default="mercadopago",
                max_length=20,
            ),
        ),
    ]
