# Generated by Django 6.0.5 on 2026-06-29 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_paymentprovider_cash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('PUSH', 'Push')], max_length=12),
        ),
        migrations.CreateModel(
            name='NotificationDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('web', 'Web'), ('android', 'Android')], max_length=16)),
                ('provider', models.CharField(choices=[('fcm', 'Firebase Cloud Messaging')], default='fcm', max_length=16)),
                ('token', models.CharField(max_length=1024, unique=True)),
                ('device_id', models.CharField(blank=True, max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_seen', '-updated_at'),
                'indexes': [models.Index(fields=['user', 'enabled'], name='reservation_user_id_55a06f_idx'), models.Index(fields=['provider', 'platform'], name='reservation_provide_10b889_idx')],
            },
        ),
    ]
