# Generated by Django 6.0.5 on 2026-06-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_notificationlog_payload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='destination',
            field=models.CharField(max_length=1024),
        ),
    ]
